# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hicham/Desktop/projet/Raytracer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hicham/Desktop/projet/Raytracer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hicham/Desktop/projet/Raytracer/CMakeFiles /home/hicham/Desktop/projet/Raytracer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hicham/Desktop/projet/Raytracer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named raytracer

# Build rule for target.
raytracer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 raytracer
.PHONY : raytracer

# fast build rule for target.
raytracer/fast:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/build
.PHONY : raytracer/fast

#=============================================================================
# Target rules for targets named raytracer_src_lib

# Build rule for target.
raytracer_src_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 raytracer_src_lib
.PHONY : raytracer_src_lib

# fast build rule for target.
raytracer_src_lib/fast:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/build
.PHONY : raytracer_src_lib/fast

#=============================================================================
# Target rules for targets named tests/test_camera_PinholeCamera

# Build rule for target.
tests/test_camera_PinholeCamera: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_camera_PinholeCamera
.PHONY : tests/test_camera_PinholeCamera

# fast build rule for target.
tests/test_camera_PinholeCamera/fast:
	$(MAKE) -f CMakeFiles/tests/test_camera_PinholeCamera.dir/build.make CMakeFiles/tests/test_camera_PinholeCamera.dir/build
.PHONY : tests/test_camera_PinholeCamera/fast

#=============================================================================
# Target rules for targets named tests/test_engine_RaytracingEngine

# Build rule for target.
tests/test_engine_RaytracingEngine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_engine_RaytracingEngine
.PHONY : tests/test_engine_RaytracingEngine

# fast build rule for target.
tests/test_engine_RaytracingEngine/fast:
	$(MAKE) -f CMakeFiles/tests/test_engine_RaytracingEngine.dir/build.make CMakeFiles/tests/test_engine_RaytracingEngine.dir/build
.PHONY : tests/test_engine_RaytracingEngine/fast

#=============================================================================
# Target rules for targets named tests/test_gui_ObserverPattern

# Build rule for target.
tests/test_gui_ObserverPattern: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_gui_ObserverPattern
.PHONY : tests/test_gui_ObserverPattern

# fast build rule for target.
tests/test_gui_ObserverPattern/fast:
	$(MAKE) -f CMakeFiles/tests/test_gui_ObserverPattern.dir/build.make CMakeFiles/tests/test_gui_ObserverPattern.dir/build
.PHONY : tests/test_gui_ObserverPattern/fast

#=============================================================================
# Target rules for targets named tests/test_gui_WindowContent

# Build rule for target.
tests/test_gui_WindowContent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_gui_WindowContent
.PHONY : tests/test_gui_WindowContent

# fast build rule for target.
tests/test_gui_WindowContent/fast:
	$(MAKE) -f CMakeFiles/tests/test_gui_WindowContent.dir/build.make CMakeFiles/tests/test_gui_WindowContent.dir/build
.PHONY : tests/test_gui_WindowContent/fast

#=============================================================================
# Target rules for targets named tests/test_gui_WindowModel

# Build rule for target.
tests/test_gui_WindowModel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_gui_WindowModel
.PHONY : tests/test_gui_WindowModel

# fast build rule for target.
tests/test_gui_WindowModel/fast:
	$(MAKE) -f CMakeFiles/tests/test_gui_WindowModel.dir/build.make CMakeFiles/tests/test_gui_WindowModel.dir/build
.PHONY : tests/test_gui_WindowModel/fast

#=============================================================================
# Target rules for targets named tests/test_gui_WindowView

# Build rule for target.
tests/test_gui_WindowView: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_gui_WindowView
.PHONY : tests/test_gui_WindowView

# fast build rule for target.
tests/test_gui_WindowView/fast:
	$(MAKE) -f CMakeFiles/tests/test_gui_WindowView.dir/build.make CMakeFiles/tests/test_gui_WindowView.dir/build
.PHONY : tests/test_gui_WindowView/fast

#=============================================================================
# Target rules for targets named tests/test_gui_sfml

# Build rule for target.
tests/test_gui_sfml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_gui_sfml
.PHONY : tests/test_gui_sfml

# fast build rule for target.
tests/test_gui_sfml/fast:
	$(MAKE) -f CMakeFiles/tests/test_gui_sfml.dir/build.make CMakeFiles/tests/test_gui_sfml.dir/build
.PHONY : tests/test_gui_sfml/fast

#=============================================================================
# Target rules for targets named tests/test_light_LightPoint

# Build rule for target.
tests/test_light_LightPoint: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_light_LightPoint
.PHONY : tests/test_light_LightPoint

# fast build rule for target.
tests/test_light_LightPoint/fast:
	$(MAKE) -f CMakeFiles/tests/test_light_LightPoint.dir/build.make CMakeFiles/tests/test_light_LightPoint.dir/build
.PHONY : tests/test_light_LightPoint/fast

#=============================================================================
# Target rules for targets named tests/test_materials_MaterialsProperties

# Build rule for target.
tests/test_materials_MaterialsProperties: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_materials_MaterialsProperties
.PHONY : tests/test_materials_MaterialsProperties

# fast build rule for target.
tests/test_materials_MaterialsProperties/fast:
	$(MAKE) -f CMakeFiles/tests/test_materials_MaterialsProperties.dir/build.make CMakeFiles/tests/test_materials_MaterialsProperties.dir/build
.PHONY : tests/test_materials_MaterialsProperties/fast

#=============================================================================
# Target rules for targets named tests/test_math_quadratic

# Build rule for target.
tests/test_math_quadratic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_math_quadratic
.PHONY : tests/test_math_quadratic

# fast build rule for target.
tests/test_math_quadratic/fast:
	$(MAKE) -f CMakeFiles/tests/test_math_quadratic.dir/build.make CMakeFiles/tests/test_math_quadratic.dir/build
.PHONY : tests/test_math_quadratic/fast

#=============================================================================
# Target rules for targets named tests/test_ray_Ray

# Build rule for target.
tests/test_ray_Ray: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_ray_Ray
.PHONY : tests/test_ray_Ray

# fast build rule for target.
tests/test_ray_Ray/fast:
	$(MAKE) -f CMakeFiles/tests/test_ray_Ray.dir/build.make CMakeFiles/tests/test_ray_Ray.dir/build
.PHONY : tests/test_ray_Ray/fast

#=============================================================================
# Target rules for targets named tests/test_sphere_intersection

# Build rule for target.
tests/test_sphere_intersection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/test_sphere_intersection
.PHONY : tests/test_sphere_intersection

# fast build rule for target.
tests/test_sphere_intersection/fast:
	$(MAKE) -f CMakeFiles/tests/test_sphere_intersection.dir/build.make CMakeFiles/tests/test_sphere_intersection.dir/build
.PHONY : tests/test_sphere_intersection/fast

src/camera/src/Camera.o: src/camera/src/Camera.cpp.o
.PHONY : src/camera/src/Camera.o

# target to build an object file
src/camera/src/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/camera/src/Camera.cpp.o
.PHONY : src/camera/src/Camera.cpp.o

src/camera/src/Camera.i: src/camera/src/Camera.cpp.i
.PHONY : src/camera/src/Camera.i

# target to preprocess a source file
src/camera/src/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/camera/src/Camera.cpp.i
.PHONY : src/camera/src/Camera.cpp.i

src/camera/src/Camera.s: src/camera/src/Camera.cpp.s
.PHONY : src/camera/src/Camera.s

# target to generate assembly for a file
src/camera/src/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/camera/src/Camera.cpp.s
.PHONY : src/camera/src/Camera.cpp.s

src/camera/src/PinholeCamera.o: src/camera/src/PinholeCamera.cpp.o
.PHONY : src/camera/src/PinholeCamera.o

# target to build an object file
src/camera/src/PinholeCamera.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/camera/src/PinholeCamera.cpp.o
.PHONY : src/camera/src/PinholeCamera.cpp.o

src/camera/src/PinholeCamera.i: src/camera/src/PinholeCamera.cpp.i
.PHONY : src/camera/src/PinholeCamera.i

# target to preprocess a source file
src/camera/src/PinholeCamera.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/camera/src/PinholeCamera.cpp.i
.PHONY : src/camera/src/PinholeCamera.cpp.i

src/camera/src/PinholeCamera.s: src/camera/src/PinholeCamera.cpp.s
.PHONY : src/camera/src/PinholeCamera.s

# target to generate assembly for a file
src/camera/src/PinholeCamera.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/camera/src/PinholeCamera.cpp.s
.PHONY : src/camera/src/PinholeCamera.cpp.s

src/camera/tests/test_camera_PinholeCamera.o: src/camera/tests/test_camera_PinholeCamera.cpp.o
.PHONY : src/camera/tests/test_camera_PinholeCamera.o

# target to build an object file
src/camera/tests/test_camera_PinholeCamera.cpp.o:
	$(MAKE) -f CMakeFiles/tests/test_camera_PinholeCamera.dir/build.make CMakeFiles/tests/test_camera_PinholeCamera.dir/src/camera/tests/test_camera_PinholeCamera.cpp.o
.PHONY : src/camera/tests/test_camera_PinholeCamera.cpp.o

src/camera/tests/test_camera_PinholeCamera.i: src/camera/tests/test_camera_PinholeCamera.cpp.i
.PHONY : src/camera/tests/test_camera_PinholeCamera.i

# target to preprocess a source file
src/camera/tests/test_camera_PinholeCamera.cpp.i:
	$(MAKE) -f CMakeFiles/tests/test_camera_PinholeCamera.dir/build.make CMakeFiles/tests/test_camera_PinholeCamera.dir/src/camera/tests/test_camera_PinholeCamera.cpp.i
.PHONY : src/camera/tests/test_camera_PinholeCamera.cpp.i

src/camera/tests/test_camera_PinholeCamera.s: src/camera/tests/test_camera_PinholeCamera.cpp.s
.PHONY : src/camera/tests/test_camera_PinholeCamera.s

# target to generate assembly for a file
src/camera/tests/test_camera_PinholeCamera.cpp.s:
	$(MAKE) -f CMakeFiles/tests/test_camera_PinholeCamera.dir/build.make CMakeFiles/tests/test_camera_PinholeCamera.dir/src/camera/tests/test_camera_PinholeCamera.cpp.s
.PHONY : src/camera/tests/test_camera_PinholeCamera.cpp.s

src/engine/src/RaytracingEngine.o: src/engine/src/RaytracingEngine.cpp.o
.PHONY : src/engine/src/RaytracingEngine.o

# target to build an object file
src/engine/src/RaytracingEngine.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/engine/src/RaytracingEngine.cpp.o
.PHONY : src/engine/src/RaytracingEngine.cpp.o

src/engine/src/RaytracingEngine.i: src/engine/src/RaytracingEngine.cpp.i
.PHONY : src/engine/src/RaytracingEngine.i

# target to preprocess a source file
src/engine/src/RaytracingEngine.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/engine/src/RaytracingEngine.cpp.i
.PHONY : src/engine/src/RaytracingEngine.cpp.i

src/engine/src/RaytracingEngine.s: src/engine/src/RaytracingEngine.cpp.s
.PHONY : src/engine/src/RaytracingEngine.s

# target to generate assembly for a file
src/engine/src/RaytracingEngine.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/engine/src/RaytracingEngine.cpp.s
.PHONY : src/engine/src/RaytracingEngine.cpp.s

src/engine/tests/test_engine_RaytracingEngine.o: src/engine/tests/test_engine_RaytracingEngine.cpp.o
.PHONY : src/engine/tests/test_engine_RaytracingEngine.o

# target to build an object file
src/engine/tests/test_engine_RaytracingEngine.cpp.o:
	$(MAKE) -f CMakeFiles/tests/test_engine_RaytracingEngine.dir/build.make CMakeFiles/tests/test_engine_RaytracingEngine.dir/src/engine/tests/test_engine_RaytracingEngine.cpp.o
.PHONY : src/engine/tests/test_engine_RaytracingEngine.cpp.o

src/engine/tests/test_engine_RaytracingEngine.i: src/engine/tests/test_engine_RaytracingEngine.cpp.i
.PHONY : src/engine/tests/test_engine_RaytracingEngine.i

# target to preprocess a source file
src/engine/tests/test_engine_RaytracingEngine.cpp.i:
	$(MAKE) -f CMakeFiles/tests/test_engine_RaytracingEngine.dir/build.make CMakeFiles/tests/test_engine_RaytracingEngine.dir/src/engine/tests/test_engine_RaytracingEngine.cpp.i
.PHONY : src/engine/tests/test_engine_RaytracingEngine.cpp.i

src/engine/tests/test_engine_RaytracingEngine.s: src/engine/tests/test_engine_RaytracingEngine.cpp.s
.PHONY : src/engine/tests/test_engine_RaytracingEngine.s

# target to generate assembly for a file
src/engine/tests/test_engine_RaytracingEngine.cpp.s:
	$(MAKE) -f CMakeFiles/tests/test_engine_RaytracingEngine.dir/build.make CMakeFiles/tests/test_engine_RaytracingEngine.dir/src/engine/tests/test_engine_RaytracingEngine.cpp.s
.PHONY : src/engine/tests/test_engine_RaytracingEngine.cpp.s

src/glutils/src/Buffers.o: src/glutils/src/Buffers.cpp.o
.PHONY : src/glutils/src/Buffers.o

# target to build an object file
src/glutils/src/Buffers.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/glutils/src/Buffers.cpp.o
.PHONY : src/glutils/src/Buffers.cpp.o

src/glutils/src/Buffers.i: src/glutils/src/Buffers.cpp.i
.PHONY : src/glutils/src/Buffers.i

# target to preprocess a source file
src/glutils/src/Buffers.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/glutils/src/Buffers.cpp.i
.PHONY : src/glutils/src/Buffers.cpp.i

src/glutils/src/Buffers.s: src/glutils/src/Buffers.cpp.s
.PHONY : src/glutils/src/Buffers.s

# target to generate assembly for a file
src/glutils/src/Buffers.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/glutils/src/Buffers.cpp.s
.PHONY : src/glutils/src/Buffers.cpp.s

src/glutils/src/Vao.o: src/glutils/src/Vao.cpp.o
.PHONY : src/glutils/src/Vao.o

# target to build an object file
src/glutils/src/Vao.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/glutils/src/Vao.cpp.o
.PHONY : src/glutils/src/Vao.cpp.o

src/glutils/src/Vao.i: src/glutils/src/Vao.cpp.i
.PHONY : src/glutils/src/Vao.i

# target to preprocess a source file
src/glutils/src/Vao.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/glutils/src/Vao.cpp.i
.PHONY : src/glutils/src/Vao.cpp.i

src/glutils/src/Vao.s: src/glutils/src/Vao.cpp.s
.PHONY : src/glutils/src/Vao.s

# target to generate assembly for a file
src/glutils/src/Vao.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/glutils/src/Vao.cpp.s
.PHONY : src/glutils/src/Vao.cpp.s

src/glutils/src/utilsTexture2D.o: src/glutils/src/utilsTexture2D.cpp.o
.PHONY : src/glutils/src/utilsTexture2D.o

# target to build an object file
src/glutils/src/utilsTexture2D.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/glutils/src/utilsTexture2D.cpp.o
.PHONY : src/glutils/src/utilsTexture2D.cpp.o

src/glutils/src/utilsTexture2D.i: src/glutils/src/utilsTexture2D.cpp.i
.PHONY : src/glutils/src/utilsTexture2D.i

# target to preprocess a source file
src/glutils/src/utilsTexture2D.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/glutils/src/utilsTexture2D.cpp.i
.PHONY : src/glutils/src/utilsTexture2D.cpp.i

src/glutils/src/utilsTexture2D.s: src/glutils/src/utilsTexture2D.cpp.s
.PHONY : src/glutils/src/utilsTexture2D.s

# target to generate assembly for a file
src/glutils/src/utilsTexture2D.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/glutils/src/utilsTexture2D.cpp.s
.PHONY : src/glutils/src/utilsTexture2D.cpp.s

src/gui/src/ImageContent.o: src/gui/src/ImageContent.cpp.o
.PHONY : src/gui/src/ImageContent.o

# target to build an object file
src/gui/src/ImageContent.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/gui/src/ImageContent.cpp.o
.PHONY : src/gui/src/ImageContent.cpp.o

src/gui/src/ImageContent.i: src/gui/src/ImageContent.cpp.i
.PHONY : src/gui/src/ImageContent.i

# target to preprocess a source file
src/gui/src/ImageContent.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/gui/src/ImageContent.cpp.i
.PHONY : src/gui/src/ImageContent.cpp.i

src/gui/src/ImageContent.s: src/gui/src/ImageContent.cpp.s
.PHONY : src/gui/src/ImageContent.s

# target to generate assembly for a file
src/gui/src/ImageContent.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/gui/src/ImageContent.cpp.s
.PHONY : src/gui/src/ImageContent.cpp.s

src/gui/src/TriangleContent.o: src/gui/src/TriangleContent.cpp.o
.PHONY : src/gui/src/TriangleContent.o

# target to build an object file
src/gui/src/TriangleContent.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/gui/src/TriangleContent.cpp.o
.PHONY : src/gui/src/TriangleContent.cpp.o

src/gui/src/TriangleContent.i: src/gui/src/TriangleContent.cpp.i
.PHONY : src/gui/src/TriangleContent.i

# target to preprocess a source file
src/gui/src/TriangleContent.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/gui/src/TriangleContent.cpp.i
.PHONY : src/gui/src/TriangleContent.cpp.i

src/gui/src/TriangleContent.s: src/gui/src/TriangleContent.cpp.s
.PHONY : src/gui/src/TriangleContent.s

# target to generate assembly for a file
src/gui/src/TriangleContent.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/gui/src/TriangleContent.cpp.s
.PHONY : src/gui/src/TriangleContent.cpp.s

src/gui/src/WindowContent.o: src/gui/src/WindowContent.cpp.o
.PHONY : src/gui/src/WindowContent.o

# target to build an object file
src/gui/src/WindowContent.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/gui/src/WindowContent.cpp.o
.PHONY : src/gui/src/WindowContent.cpp.o

src/gui/src/WindowContent.i: src/gui/src/WindowContent.cpp.i
.PHONY : src/gui/src/WindowContent.i

# target to preprocess a source file
src/gui/src/WindowContent.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/gui/src/WindowContent.cpp.i
.PHONY : src/gui/src/WindowContent.cpp.i

src/gui/src/WindowContent.s: src/gui/src/WindowContent.cpp.s
.PHONY : src/gui/src/WindowContent.s

# target to generate assembly for a file
src/gui/src/WindowContent.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/gui/src/WindowContent.cpp.s
.PHONY : src/gui/src/WindowContent.cpp.s

src/gui/src/WindowController.o: src/gui/src/WindowController.cpp.o
.PHONY : src/gui/src/WindowController.o

# target to build an object file
src/gui/src/WindowController.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/gui/src/WindowController.cpp.o
.PHONY : src/gui/src/WindowController.cpp.o

src/gui/src/WindowController.i: src/gui/src/WindowController.cpp.i
.PHONY : src/gui/src/WindowController.i

# target to preprocess a source file
src/gui/src/WindowController.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/gui/src/WindowController.cpp.i
.PHONY : src/gui/src/WindowController.cpp.i

src/gui/src/WindowController.s: src/gui/src/WindowController.cpp.s
.PHONY : src/gui/src/WindowController.s

# target to generate assembly for a file
src/gui/src/WindowController.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/gui/src/WindowController.cpp.s
.PHONY : src/gui/src/WindowController.cpp.s

src/gui/src/WindowEvent.o: src/gui/src/WindowEvent.cpp.o
.PHONY : src/gui/src/WindowEvent.o

# target to build an object file
src/gui/src/WindowEvent.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/gui/src/WindowEvent.cpp.o
.PHONY : src/gui/src/WindowEvent.cpp.o

src/gui/src/WindowEvent.i: src/gui/src/WindowEvent.cpp.i
.PHONY : src/gui/src/WindowEvent.i

# target to preprocess a source file
src/gui/src/WindowEvent.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/gui/src/WindowEvent.cpp.i
.PHONY : src/gui/src/WindowEvent.cpp.i

src/gui/src/WindowEvent.s: src/gui/src/WindowEvent.cpp.s
.PHONY : src/gui/src/WindowEvent.s

# target to generate assembly for a file
src/gui/src/WindowEvent.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/gui/src/WindowEvent.cpp.s
.PHONY : src/gui/src/WindowEvent.cpp.s

src/gui/src/WindowModel.o: src/gui/src/WindowModel.cpp.o
.PHONY : src/gui/src/WindowModel.o

# target to build an object file
src/gui/src/WindowModel.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/gui/src/WindowModel.cpp.o
.PHONY : src/gui/src/WindowModel.cpp.o

src/gui/src/WindowModel.i: src/gui/src/WindowModel.cpp.i
.PHONY : src/gui/src/WindowModel.i

# target to preprocess a source file
src/gui/src/WindowModel.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/gui/src/WindowModel.cpp.i
.PHONY : src/gui/src/WindowModel.cpp.i

src/gui/src/WindowModel.s: src/gui/src/WindowModel.cpp.s
.PHONY : src/gui/src/WindowModel.s

# target to generate assembly for a file
src/gui/src/WindowModel.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/gui/src/WindowModel.cpp.s
.PHONY : src/gui/src/WindowModel.cpp.s

src/gui/src/WindowView.o: src/gui/src/WindowView.cpp.o
.PHONY : src/gui/src/WindowView.o

# target to build an object file
src/gui/src/WindowView.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/gui/src/WindowView.cpp.o
.PHONY : src/gui/src/WindowView.cpp.o

src/gui/src/WindowView.i: src/gui/src/WindowView.cpp.i
.PHONY : src/gui/src/WindowView.i

# target to preprocess a source file
src/gui/src/WindowView.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/gui/src/WindowView.cpp.i
.PHONY : src/gui/src/WindowView.cpp.i

src/gui/src/WindowView.s: src/gui/src/WindowView.cpp.s
.PHONY : src/gui/src/WindowView.s

# target to generate assembly for a file
src/gui/src/WindowView.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/gui/src/WindowView.cpp.s
.PHONY : src/gui/src/WindowView.cpp.s

src/gui/tests/test_gui_ObserverPattern.o: src/gui/tests/test_gui_ObserverPattern.cpp.o
.PHONY : src/gui/tests/test_gui_ObserverPattern.o

# target to build an object file
src/gui/tests/test_gui_ObserverPattern.cpp.o:
	$(MAKE) -f CMakeFiles/tests/test_gui_ObserverPattern.dir/build.make CMakeFiles/tests/test_gui_ObserverPattern.dir/src/gui/tests/test_gui_ObserverPattern.cpp.o
.PHONY : src/gui/tests/test_gui_ObserverPattern.cpp.o

src/gui/tests/test_gui_ObserverPattern.i: src/gui/tests/test_gui_ObserverPattern.cpp.i
.PHONY : src/gui/tests/test_gui_ObserverPattern.i

# target to preprocess a source file
src/gui/tests/test_gui_ObserverPattern.cpp.i:
	$(MAKE) -f CMakeFiles/tests/test_gui_ObserverPattern.dir/build.make CMakeFiles/tests/test_gui_ObserverPattern.dir/src/gui/tests/test_gui_ObserverPattern.cpp.i
.PHONY : src/gui/tests/test_gui_ObserverPattern.cpp.i

src/gui/tests/test_gui_ObserverPattern.s: src/gui/tests/test_gui_ObserverPattern.cpp.s
.PHONY : src/gui/tests/test_gui_ObserverPattern.s

# target to generate assembly for a file
src/gui/tests/test_gui_ObserverPattern.cpp.s:
	$(MAKE) -f CMakeFiles/tests/test_gui_ObserverPattern.dir/build.make CMakeFiles/tests/test_gui_ObserverPattern.dir/src/gui/tests/test_gui_ObserverPattern.cpp.s
.PHONY : src/gui/tests/test_gui_ObserverPattern.cpp.s

src/gui/tests/test_gui_WindowContent.o: src/gui/tests/test_gui_WindowContent.cpp.o
.PHONY : src/gui/tests/test_gui_WindowContent.o

# target to build an object file
src/gui/tests/test_gui_WindowContent.cpp.o:
	$(MAKE) -f CMakeFiles/tests/test_gui_WindowContent.dir/build.make CMakeFiles/tests/test_gui_WindowContent.dir/src/gui/tests/test_gui_WindowContent.cpp.o
.PHONY : src/gui/tests/test_gui_WindowContent.cpp.o

src/gui/tests/test_gui_WindowContent.i: src/gui/tests/test_gui_WindowContent.cpp.i
.PHONY : src/gui/tests/test_gui_WindowContent.i

# target to preprocess a source file
src/gui/tests/test_gui_WindowContent.cpp.i:
	$(MAKE) -f CMakeFiles/tests/test_gui_WindowContent.dir/build.make CMakeFiles/tests/test_gui_WindowContent.dir/src/gui/tests/test_gui_WindowContent.cpp.i
.PHONY : src/gui/tests/test_gui_WindowContent.cpp.i

src/gui/tests/test_gui_WindowContent.s: src/gui/tests/test_gui_WindowContent.cpp.s
.PHONY : src/gui/tests/test_gui_WindowContent.s

# target to generate assembly for a file
src/gui/tests/test_gui_WindowContent.cpp.s:
	$(MAKE) -f CMakeFiles/tests/test_gui_WindowContent.dir/build.make CMakeFiles/tests/test_gui_WindowContent.dir/src/gui/tests/test_gui_WindowContent.cpp.s
.PHONY : src/gui/tests/test_gui_WindowContent.cpp.s

src/gui/tests/test_gui_WindowModel.o: src/gui/tests/test_gui_WindowModel.cpp.o
.PHONY : src/gui/tests/test_gui_WindowModel.o

# target to build an object file
src/gui/tests/test_gui_WindowModel.cpp.o:
	$(MAKE) -f CMakeFiles/tests/test_gui_WindowModel.dir/build.make CMakeFiles/tests/test_gui_WindowModel.dir/src/gui/tests/test_gui_WindowModel.cpp.o
.PHONY : src/gui/tests/test_gui_WindowModel.cpp.o

src/gui/tests/test_gui_WindowModel.i: src/gui/tests/test_gui_WindowModel.cpp.i
.PHONY : src/gui/tests/test_gui_WindowModel.i

# target to preprocess a source file
src/gui/tests/test_gui_WindowModel.cpp.i:
	$(MAKE) -f CMakeFiles/tests/test_gui_WindowModel.dir/build.make CMakeFiles/tests/test_gui_WindowModel.dir/src/gui/tests/test_gui_WindowModel.cpp.i
.PHONY : src/gui/tests/test_gui_WindowModel.cpp.i

src/gui/tests/test_gui_WindowModel.s: src/gui/tests/test_gui_WindowModel.cpp.s
.PHONY : src/gui/tests/test_gui_WindowModel.s

# target to generate assembly for a file
src/gui/tests/test_gui_WindowModel.cpp.s:
	$(MAKE) -f CMakeFiles/tests/test_gui_WindowModel.dir/build.make CMakeFiles/tests/test_gui_WindowModel.dir/src/gui/tests/test_gui_WindowModel.cpp.s
.PHONY : src/gui/tests/test_gui_WindowModel.cpp.s

src/gui/tests/test_gui_WindowView.o: src/gui/tests/test_gui_WindowView.cpp.o
.PHONY : src/gui/tests/test_gui_WindowView.o

# target to build an object file
src/gui/tests/test_gui_WindowView.cpp.o:
	$(MAKE) -f CMakeFiles/tests/test_gui_WindowView.dir/build.make CMakeFiles/tests/test_gui_WindowView.dir/src/gui/tests/test_gui_WindowView.cpp.o
.PHONY : src/gui/tests/test_gui_WindowView.cpp.o

src/gui/tests/test_gui_WindowView.i: src/gui/tests/test_gui_WindowView.cpp.i
.PHONY : src/gui/tests/test_gui_WindowView.i

# target to preprocess a source file
src/gui/tests/test_gui_WindowView.cpp.i:
	$(MAKE) -f CMakeFiles/tests/test_gui_WindowView.dir/build.make CMakeFiles/tests/test_gui_WindowView.dir/src/gui/tests/test_gui_WindowView.cpp.i
.PHONY : src/gui/tests/test_gui_WindowView.cpp.i

src/gui/tests/test_gui_WindowView.s: src/gui/tests/test_gui_WindowView.cpp.s
.PHONY : src/gui/tests/test_gui_WindowView.s

# target to generate assembly for a file
src/gui/tests/test_gui_WindowView.cpp.s:
	$(MAKE) -f CMakeFiles/tests/test_gui_WindowView.dir/build.make CMakeFiles/tests/test_gui_WindowView.dir/src/gui/tests/test_gui_WindowView.cpp.s
.PHONY : src/gui/tests/test_gui_WindowView.cpp.s

src/gui/tests/test_gui_sfml.o: src/gui/tests/test_gui_sfml.cpp.o
.PHONY : src/gui/tests/test_gui_sfml.o

# target to build an object file
src/gui/tests/test_gui_sfml.cpp.o:
	$(MAKE) -f CMakeFiles/tests/test_gui_sfml.dir/build.make CMakeFiles/tests/test_gui_sfml.dir/src/gui/tests/test_gui_sfml.cpp.o
.PHONY : src/gui/tests/test_gui_sfml.cpp.o

src/gui/tests/test_gui_sfml.i: src/gui/tests/test_gui_sfml.cpp.i
.PHONY : src/gui/tests/test_gui_sfml.i

# target to preprocess a source file
src/gui/tests/test_gui_sfml.cpp.i:
	$(MAKE) -f CMakeFiles/tests/test_gui_sfml.dir/build.make CMakeFiles/tests/test_gui_sfml.dir/src/gui/tests/test_gui_sfml.cpp.i
.PHONY : src/gui/tests/test_gui_sfml.cpp.i

src/gui/tests/test_gui_sfml.s: src/gui/tests/test_gui_sfml.cpp.s
.PHONY : src/gui/tests/test_gui_sfml.s

# target to generate assembly for a file
src/gui/tests/test_gui_sfml.cpp.s:
	$(MAKE) -f CMakeFiles/tests/test_gui_sfml.dir/build.make CMakeFiles/tests/test_gui_sfml.dir/src/gui/tests/test_gui_sfml.cpp.s
.PHONY : src/gui/tests/test_gui_sfml.cpp.s

src/light/src/LightPoint.o: src/light/src/LightPoint.cpp.o
.PHONY : src/light/src/LightPoint.o

# target to build an object file
src/light/src/LightPoint.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/light/src/LightPoint.cpp.o
.PHONY : src/light/src/LightPoint.cpp.o

src/light/src/LightPoint.i: src/light/src/LightPoint.cpp.i
.PHONY : src/light/src/LightPoint.i

# target to preprocess a source file
src/light/src/LightPoint.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/light/src/LightPoint.cpp.i
.PHONY : src/light/src/LightPoint.cpp.i

src/light/src/LightPoint.s: src/light/src/LightPoint.cpp.s
.PHONY : src/light/src/LightPoint.s

# target to generate assembly for a file
src/light/src/LightPoint.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/light/src/LightPoint.cpp.s
.PHONY : src/light/src/LightPoint.cpp.s

src/light/tests/test_light_LightPoint.o: src/light/tests/test_light_LightPoint.cpp.o
.PHONY : src/light/tests/test_light_LightPoint.o

# target to build an object file
src/light/tests/test_light_LightPoint.cpp.o:
	$(MAKE) -f CMakeFiles/tests/test_light_LightPoint.dir/build.make CMakeFiles/tests/test_light_LightPoint.dir/src/light/tests/test_light_LightPoint.cpp.o
.PHONY : src/light/tests/test_light_LightPoint.cpp.o

src/light/tests/test_light_LightPoint.i: src/light/tests/test_light_LightPoint.cpp.i
.PHONY : src/light/tests/test_light_LightPoint.i

# target to preprocess a source file
src/light/tests/test_light_LightPoint.cpp.i:
	$(MAKE) -f CMakeFiles/tests/test_light_LightPoint.dir/build.make CMakeFiles/tests/test_light_LightPoint.dir/src/light/tests/test_light_LightPoint.cpp.i
.PHONY : src/light/tests/test_light_LightPoint.cpp.i

src/light/tests/test_light_LightPoint.s: src/light/tests/test_light_LightPoint.cpp.s
.PHONY : src/light/tests/test_light_LightPoint.s

# target to generate assembly for a file
src/light/tests/test_light_LightPoint.cpp.s:
	$(MAKE) -f CMakeFiles/tests/test_light_LightPoint.dir/build.make CMakeFiles/tests/test_light_LightPoint.dir/src/light/tests/test_light_LightPoint.cpp.s
.PHONY : src/light/tests/test_light_LightPoint.cpp.s

src/main/main.o: src/main/main.cpp.o
.PHONY : src/main/main.o

# target to build an object file
src/main/main.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/main/main.cpp.o
.PHONY : src/main/main.cpp.o

src/main/main.i: src/main/main.cpp.i
.PHONY : src/main/main.i

# target to preprocess a source file
src/main/main.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/main/main.cpp.i
.PHONY : src/main/main.cpp.i

src/main/main.s: src/main/main.cpp.s
.PHONY : src/main/main.s

# target to generate assembly for a file
src/main/main.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/main/main.cpp.s
.PHONY : src/main/main.cpp.s

src/materials/src/Material.o: src/materials/src/Material.cpp.o
.PHONY : src/materials/src/Material.o

# target to build an object file
src/materials/src/Material.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/materials/src/Material.cpp.o
.PHONY : src/materials/src/Material.cpp.o

src/materials/src/Material.i: src/materials/src/Material.cpp.i
.PHONY : src/materials/src/Material.i

# target to preprocess a source file
src/materials/src/Material.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/materials/src/Material.cpp.i
.PHONY : src/materials/src/Material.cpp.i

src/materials/src/Material.s: src/materials/src/Material.cpp.s
.PHONY : src/materials/src/Material.s

# target to generate assembly for a file
src/materials/src/Material.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/materials/src/Material.cpp.s
.PHONY : src/materials/src/Material.cpp.s

src/materials/src/MaterialProperties.o: src/materials/src/MaterialProperties.cpp.o
.PHONY : src/materials/src/MaterialProperties.o

# target to build an object file
src/materials/src/MaterialProperties.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/materials/src/MaterialProperties.cpp.o
.PHONY : src/materials/src/MaterialProperties.cpp.o

src/materials/src/MaterialProperties.i: src/materials/src/MaterialProperties.cpp.i
.PHONY : src/materials/src/MaterialProperties.i

# target to preprocess a source file
src/materials/src/MaterialProperties.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/materials/src/MaterialProperties.cpp.i
.PHONY : src/materials/src/MaterialProperties.cpp.i

src/materials/src/MaterialProperties.s: src/materials/src/MaterialProperties.cpp.s
.PHONY : src/materials/src/MaterialProperties.s

# target to generate assembly for a file
src/materials/src/MaterialProperties.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/materials/src/MaterialProperties.cpp.s
.PHONY : src/materials/src/MaterialProperties.cpp.s

src/materials/tests/test_materials_MaterialsProperties.o: src/materials/tests/test_materials_MaterialsProperties.cpp.o
.PHONY : src/materials/tests/test_materials_MaterialsProperties.o

# target to build an object file
src/materials/tests/test_materials_MaterialsProperties.cpp.o:
	$(MAKE) -f CMakeFiles/tests/test_materials_MaterialsProperties.dir/build.make CMakeFiles/tests/test_materials_MaterialsProperties.dir/src/materials/tests/test_materials_MaterialsProperties.cpp.o
.PHONY : src/materials/tests/test_materials_MaterialsProperties.cpp.o

src/materials/tests/test_materials_MaterialsProperties.i: src/materials/tests/test_materials_MaterialsProperties.cpp.i
.PHONY : src/materials/tests/test_materials_MaterialsProperties.i

# target to preprocess a source file
src/materials/tests/test_materials_MaterialsProperties.cpp.i:
	$(MAKE) -f CMakeFiles/tests/test_materials_MaterialsProperties.dir/build.make CMakeFiles/tests/test_materials_MaterialsProperties.dir/src/materials/tests/test_materials_MaterialsProperties.cpp.i
.PHONY : src/materials/tests/test_materials_MaterialsProperties.cpp.i

src/materials/tests/test_materials_MaterialsProperties.s: src/materials/tests/test_materials_MaterialsProperties.cpp.s
.PHONY : src/materials/tests/test_materials_MaterialsProperties.s

# target to generate assembly for a file
src/materials/tests/test_materials_MaterialsProperties.cpp.s:
	$(MAKE) -f CMakeFiles/tests/test_materials_MaterialsProperties.dir/build.make CMakeFiles/tests/test_materials_MaterialsProperties.dir/src/materials/tests/test_materials_MaterialsProperties.cpp.s
.PHONY : src/materials/tests/test_materials_MaterialsProperties.cpp.s

src/math/src/Quadratic.o: src/math/src/Quadratic.cpp.o
.PHONY : src/math/src/Quadratic.o

# target to build an object file
src/math/src/Quadratic.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/math/src/Quadratic.cpp.o
.PHONY : src/math/src/Quadratic.cpp.o

src/math/src/Quadratic.i: src/math/src/Quadratic.cpp.i
.PHONY : src/math/src/Quadratic.i

# target to preprocess a source file
src/math/src/Quadratic.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/math/src/Quadratic.cpp.i
.PHONY : src/math/src/Quadratic.cpp.i

src/math/src/Quadratic.s: src/math/src/Quadratic.cpp.s
.PHONY : src/math/src/Quadratic.s

# target to generate assembly for a file
src/math/src/Quadratic.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/math/src/Quadratic.cpp.s
.PHONY : src/math/src/Quadratic.cpp.s

src/math/tests/test_math_quadratic.o: src/math/tests/test_math_quadratic.cpp.o
.PHONY : src/math/tests/test_math_quadratic.o

# target to build an object file
src/math/tests/test_math_quadratic.cpp.o:
	$(MAKE) -f CMakeFiles/tests/test_math_quadratic.dir/build.make CMakeFiles/tests/test_math_quadratic.dir/src/math/tests/test_math_quadratic.cpp.o
.PHONY : src/math/tests/test_math_quadratic.cpp.o

src/math/tests/test_math_quadratic.i: src/math/tests/test_math_quadratic.cpp.i
.PHONY : src/math/tests/test_math_quadratic.i

# target to preprocess a source file
src/math/tests/test_math_quadratic.cpp.i:
	$(MAKE) -f CMakeFiles/tests/test_math_quadratic.dir/build.make CMakeFiles/tests/test_math_quadratic.dir/src/math/tests/test_math_quadratic.cpp.i
.PHONY : src/math/tests/test_math_quadratic.cpp.i

src/math/tests/test_math_quadratic.s: src/math/tests/test_math_quadratic.cpp.s
.PHONY : src/math/tests/test_math_quadratic.s

# target to generate assembly for a file
src/math/tests/test_math_quadratic.cpp.s:
	$(MAKE) -f CMakeFiles/tests/test_math_quadratic.dir/build.make CMakeFiles/tests/test_math_quadratic.dir/src/math/tests/test_math_quadratic.cpp.s
.PHONY : src/math/tests/test_math_quadratic.cpp.s

src/ray/src/CameraRay.o: src/ray/src/CameraRay.cpp.o
.PHONY : src/ray/src/CameraRay.o

# target to build an object file
src/ray/src/CameraRay.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/ray/src/CameraRay.cpp.o
.PHONY : src/ray/src/CameraRay.cpp.o

src/ray/src/CameraRay.i: src/ray/src/CameraRay.cpp.i
.PHONY : src/ray/src/CameraRay.i

# target to preprocess a source file
src/ray/src/CameraRay.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/ray/src/CameraRay.cpp.i
.PHONY : src/ray/src/CameraRay.cpp.i

src/ray/src/CameraRay.s: src/ray/src/CameraRay.cpp.s
.PHONY : src/ray/src/CameraRay.s

# target to generate assembly for a file
src/ray/src/CameraRay.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/ray/src/CameraRay.cpp.s
.PHONY : src/ray/src/CameraRay.cpp.s

src/ray/src/Ray.o: src/ray/src/Ray.cpp.o
.PHONY : src/ray/src/Ray.o

# target to build an object file
src/ray/src/Ray.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/ray/src/Ray.cpp.o
.PHONY : src/ray/src/Ray.cpp.o

src/ray/src/Ray.i: src/ray/src/Ray.cpp.i
.PHONY : src/ray/src/Ray.i

# target to preprocess a source file
src/ray/src/Ray.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/ray/src/Ray.cpp.i
.PHONY : src/ray/src/Ray.cpp.i

src/ray/src/Ray.s: src/ray/src/Ray.cpp.s
.PHONY : src/ray/src/Ray.s

# target to generate assembly for a file
src/ray/src/Ray.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/ray/src/Ray.cpp.s
.PHONY : src/ray/src/Ray.cpp.s

src/ray/src/ReflexionRay.o: src/ray/src/ReflexionRay.cpp.o
.PHONY : src/ray/src/ReflexionRay.o

# target to build an object file
src/ray/src/ReflexionRay.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/ray/src/ReflexionRay.cpp.o
.PHONY : src/ray/src/ReflexionRay.cpp.o

src/ray/src/ReflexionRay.i: src/ray/src/ReflexionRay.cpp.i
.PHONY : src/ray/src/ReflexionRay.i

# target to preprocess a source file
src/ray/src/ReflexionRay.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/ray/src/ReflexionRay.cpp.i
.PHONY : src/ray/src/ReflexionRay.cpp.i

src/ray/src/ReflexionRay.s: src/ray/src/ReflexionRay.cpp.s
.PHONY : src/ray/src/ReflexionRay.s

# target to generate assembly for a file
src/ray/src/ReflexionRay.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/ray/src/ReflexionRay.cpp.s
.PHONY : src/ray/src/ReflexionRay.cpp.s

src/ray/src/ShadowRay.o: src/ray/src/ShadowRay.cpp.o
.PHONY : src/ray/src/ShadowRay.o

# target to build an object file
src/ray/src/ShadowRay.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/ray/src/ShadowRay.cpp.o
.PHONY : src/ray/src/ShadowRay.cpp.o

src/ray/src/ShadowRay.i: src/ray/src/ShadowRay.cpp.i
.PHONY : src/ray/src/ShadowRay.i

# target to preprocess a source file
src/ray/src/ShadowRay.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/ray/src/ShadowRay.cpp.i
.PHONY : src/ray/src/ShadowRay.cpp.i

src/ray/src/ShadowRay.s: src/ray/src/ShadowRay.cpp.s
.PHONY : src/ray/src/ShadowRay.s

# target to generate assembly for a file
src/ray/src/ShadowRay.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/ray/src/ShadowRay.cpp.s
.PHONY : src/ray/src/ShadowRay.cpp.s

src/ray/src/TransmissionRay.o: src/ray/src/TransmissionRay.cpp.o
.PHONY : src/ray/src/TransmissionRay.o

# target to build an object file
src/ray/src/TransmissionRay.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/ray/src/TransmissionRay.cpp.o
.PHONY : src/ray/src/TransmissionRay.cpp.o

src/ray/src/TransmissionRay.i: src/ray/src/TransmissionRay.cpp.i
.PHONY : src/ray/src/TransmissionRay.i

# target to preprocess a source file
src/ray/src/TransmissionRay.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/ray/src/TransmissionRay.cpp.i
.PHONY : src/ray/src/TransmissionRay.cpp.i

src/ray/src/TransmissionRay.s: src/ray/src/TransmissionRay.cpp.s
.PHONY : src/ray/src/TransmissionRay.s

# target to generate assembly for a file
src/ray/src/TransmissionRay.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/ray/src/TransmissionRay.cpp.s
.PHONY : src/ray/src/TransmissionRay.cpp.s

src/ray/tests/test_ray_Ray.o: src/ray/tests/test_ray_Ray.cpp.o
.PHONY : src/ray/tests/test_ray_Ray.o

# target to build an object file
src/ray/tests/test_ray_Ray.cpp.o:
	$(MAKE) -f CMakeFiles/tests/test_ray_Ray.dir/build.make CMakeFiles/tests/test_ray_Ray.dir/src/ray/tests/test_ray_Ray.cpp.o
.PHONY : src/ray/tests/test_ray_Ray.cpp.o

src/ray/tests/test_ray_Ray.i: src/ray/tests/test_ray_Ray.cpp.i
.PHONY : src/ray/tests/test_ray_Ray.i

# target to preprocess a source file
src/ray/tests/test_ray_Ray.cpp.i:
	$(MAKE) -f CMakeFiles/tests/test_ray_Ray.dir/build.make CMakeFiles/tests/test_ray_Ray.dir/src/ray/tests/test_ray_Ray.cpp.i
.PHONY : src/ray/tests/test_ray_Ray.cpp.i

src/ray/tests/test_ray_Ray.s: src/ray/tests/test_ray_Ray.cpp.s
.PHONY : src/ray/tests/test_ray_Ray.s

# target to generate assembly for a file
src/ray/tests/test_ray_Ray.cpp.s:
	$(MAKE) -f CMakeFiles/tests/test_ray_Ray.dir/build.make CMakeFiles/tests/test_ray_Ray.dir/src/ray/tests/test_ray_Ray.cpp.s
.PHONY : src/ray/tests/test_ray_Ray.cpp.s

src/scene/src/Intersection.o: src/scene/src/Intersection.cpp.o
.PHONY : src/scene/src/Intersection.o

# target to build an object file
src/scene/src/Intersection.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/scene/src/Intersection.cpp.o
.PHONY : src/scene/src/Intersection.cpp.o

src/scene/src/Intersection.i: src/scene/src/Intersection.cpp.i
.PHONY : src/scene/src/Intersection.i

# target to preprocess a source file
src/scene/src/Intersection.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/scene/src/Intersection.cpp.i
.PHONY : src/scene/src/Intersection.cpp.i

src/scene/src/Intersection.s: src/scene/src/Intersection.cpp.s
.PHONY : src/scene/src/Intersection.s

# target to generate assembly for a file
src/scene/src/Intersection.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/scene/src/Intersection.cpp.s
.PHONY : src/scene/src/Intersection.cpp.s

src/scene/src/Object.o: src/scene/src/Object.cpp.o
.PHONY : src/scene/src/Object.o

# target to build an object file
src/scene/src/Object.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/scene/src/Object.cpp.o
.PHONY : src/scene/src/Object.cpp.o

src/scene/src/Object.i: src/scene/src/Object.cpp.i
.PHONY : src/scene/src/Object.i

# target to preprocess a source file
src/scene/src/Object.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/scene/src/Object.cpp.i
.PHONY : src/scene/src/Object.cpp.i

src/scene/src/Object.s: src/scene/src/Object.cpp.s
.PHONY : src/scene/src/Object.s

# target to generate assembly for a file
src/scene/src/Object.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/scene/src/Object.cpp.s
.PHONY : src/scene/src/Object.cpp.s

src/scene/src/Scene.o: src/scene/src/Scene.cpp.o
.PHONY : src/scene/src/Scene.o

# target to build an object file
src/scene/src/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/scene/src/Scene.cpp.o
.PHONY : src/scene/src/Scene.cpp.o

src/scene/src/Scene.i: src/scene/src/Scene.cpp.i
.PHONY : src/scene/src/Scene.i

# target to preprocess a source file
src/scene/src/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/scene/src/Scene.cpp.i
.PHONY : src/scene/src/Scene.cpp.i

src/scene/src/Scene.s: src/scene/src/Scene.cpp.s
.PHONY : src/scene/src/Scene.s

# target to generate assembly for a file
src/scene/src/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/scene/src/Scene.cpp.s
.PHONY : src/scene/src/Scene.cpp.s

src/scene/src/Shape.o: src/scene/src/Shape.cpp.o
.PHONY : src/scene/src/Shape.o

# target to build an object file
src/scene/src/Shape.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/scene/src/Shape.cpp.o
.PHONY : src/scene/src/Shape.cpp.o

src/scene/src/Shape.i: src/scene/src/Shape.cpp.i
.PHONY : src/scene/src/Shape.i

# target to preprocess a source file
src/scene/src/Shape.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/scene/src/Shape.cpp.i
.PHONY : src/scene/src/Shape.cpp.i

src/scene/src/Shape.s: src/scene/src/Shape.cpp.s
.PHONY : src/scene/src/Shape.s

# target to generate assembly for a file
src/scene/src/Shape.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/scene/src/Shape.cpp.s
.PHONY : src/scene/src/Shape.cpp.s

src/scene/src/Sphere.o: src/scene/src/Sphere.cpp.o
.PHONY : src/scene/src/Sphere.o

# target to build an object file
src/scene/src/Sphere.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/scene/src/Sphere.cpp.o
.PHONY : src/scene/src/Sphere.cpp.o

src/scene/src/Sphere.i: src/scene/src/Sphere.cpp.i
.PHONY : src/scene/src/Sphere.i

# target to preprocess a source file
src/scene/src/Sphere.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/scene/src/Sphere.cpp.i
.PHONY : src/scene/src/Sphere.cpp.i

src/scene/src/Sphere.s: src/scene/src/Sphere.cpp.s
.PHONY : src/scene/src/Sphere.s

# target to generate assembly for a file
src/scene/src/Sphere.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer_src_lib.dir/build.make CMakeFiles/raytracer_src_lib.dir/src/scene/src/Sphere.cpp.s
.PHONY : src/scene/src/Sphere.cpp.s

src/scene/tests/test_sphere_intersection.o: src/scene/tests/test_sphere_intersection.cpp.o
.PHONY : src/scene/tests/test_sphere_intersection.o

# target to build an object file
src/scene/tests/test_sphere_intersection.cpp.o:
	$(MAKE) -f CMakeFiles/tests/test_sphere_intersection.dir/build.make CMakeFiles/tests/test_sphere_intersection.dir/src/scene/tests/test_sphere_intersection.cpp.o
.PHONY : src/scene/tests/test_sphere_intersection.cpp.o

src/scene/tests/test_sphere_intersection.i: src/scene/tests/test_sphere_intersection.cpp.i
.PHONY : src/scene/tests/test_sphere_intersection.i

# target to preprocess a source file
src/scene/tests/test_sphere_intersection.cpp.i:
	$(MAKE) -f CMakeFiles/tests/test_sphere_intersection.dir/build.make CMakeFiles/tests/test_sphere_intersection.dir/src/scene/tests/test_sphere_intersection.cpp.i
.PHONY : src/scene/tests/test_sphere_intersection.cpp.i

src/scene/tests/test_sphere_intersection.s: src/scene/tests/test_sphere_intersection.cpp.s
.PHONY : src/scene/tests/test_sphere_intersection.s

# target to generate assembly for a file
src/scene/tests/test_sphere_intersection.cpp.s:
	$(MAKE) -f CMakeFiles/tests/test_sphere_intersection.dir/build.make CMakeFiles/tests/test_sphere_intersection.dir/src/scene/tests/test_sphere_intersection.cpp.s
.PHONY : src/scene/tests/test_sphere_intersection.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... raytracer"
	@echo "... raytracer_src_lib"
	@echo "... rebuild_cache"
	@echo "... tests/test_camera_PinholeCamera"
	@echo "... tests/test_engine_RaytracingEngine"
	@echo "... tests/test_gui_ObserverPattern"
	@echo "... tests/test_gui_WindowContent"
	@echo "... tests/test_gui_WindowModel"
	@echo "... tests/test_gui_WindowView"
	@echo "... tests/test_gui_sfml"
	@echo "... tests/test_light_LightPoint"
	@echo "... tests/test_materials_MaterialsProperties"
	@echo "... tests/test_math_quadratic"
	@echo "... tests/test_ray_Ray"
	@echo "... tests/test_sphere_intersection"
	@echo "... src/camera/src/Camera.o"
	@echo "... src/camera/src/Camera.i"
	@echo "... src/camera/src/Camera.s"
	@echo "... src/camera/src/PinholeCamera.o"
	@echo "... src/camera/src/PinholeCamera.i"
	@echo "... src/camera/src/PinholeCamera.s"
	@echo "... src/camera/tests/test_camera_PinholeCamera.o"
	@echo "... src/camera/tests/test_camera_PinholeCamera.i"
	@echo "... src/camera/tests/test_camera_PinholeCamera.s"
	@echo "... src/engine/src/RaytracingEngine.o"
	@echo "... src/engine/src/RaytracingEngine.i"
	@echo "... src/engine/src/RaytracingEngine.s"
	@echo "... src/engine/tests/test_engine_RaytracingEngine.o"
	@echo "... src/engine/tests/test_engine_RaytracingEngine.i"
	@echo "... src/engine/tests/test_engine_RaytracingEngine.s"
	@echo "... src/glutils/src/Buffers.o"
	@echo "... src/glutils/src/Buffers.i"
	@echo "... src/glutils/src/Buffers.s"
	@echo "... src/glutils/src/Vao.o"
	@echo "... src/glutils/src/Vao.i"
	@echo "... src/glutils/src/Vao.s"
	@echo "... src/glutils/src/utilsTexture2D.o"
	@echo "... src/glutils/src/utilsTexture2D.i"
	@echo "... src/glutils/src/utilsTexture2D.s"
	@echo "... src/gui/src/ImageContent.o"
	@echo "... src/gui/src/ImageContent.i"
	@echo "... src/gui/src/ImageContent.s"
	@echo "... src/gui/src/TriangleContent.o"
	@echo "... src/gui/src/TriangleContent.i"
	@echo "... src/gui/src/TriangleContent.s"
	@echo "... src/gui/src/WindowContent.o"
	@echo "... src/gui/src/WindowContent.i"
	@echo "... src/gui/src/WindowContent.s"
	@echo "... src/gui/src/WindowController.o"
	@echo "... src/gui/src/WindowController.i"
	@echo "... src/gui/src/WindowController.s"
	@echo "... src/gui/src/WindowEvent.o"
	@echo "... src/gui/src/WindowEvent.i"
	@echo "... src/gui/src/WindowEvent.s"
	@echo "... src/gui/src/WindowModel.o"
	@echo "... src/gui/src/WindowModel.i"
	@echo "... src/gui/src/WindowModel.s"
	@echo "... src/gui/src/WindowView.o"
	@echo "... src/gui/src/WindowView.i"
	@echo "... src/gui/src/WindowView.s"
	@echo "... src/gui/tests/test_gui_ObserverPattern.o"
	@echo "... src/gui/tests/test_gui_ObserverPattern.i"
	@echo "... src/gui/tests/test_gui_ObserverPattern.s"
	@echo "... src/gui/tests/test_gui_WindowContent.o"
	@echo "... src/gui/tests/test_gui_WindowContent.i"
	@echo "... src/gui/tests/test_gui_WindowContent.s"
	@echo "... src/gui/tests/test_gui_WindowModel.o"
	@echo "... src/gui/tests/test_gui_WindowModel.i"
	@echo "... src/gui/tests/test_gui_WindowModel.s"
	@echo "... src/gui/tests/test_gui_WindowView.o"
	@echo "... src/gui/tests/test_gui_WindowView.i"
	@echo "... src/gui/tests/test_gui_WindowView.s"
	@echo "... src/gui/tests/test_gui_sfml.o"
	@echo "... src/gui/tests/test_gui_sfml.i"
	@echo "... src/gui/tests/test_gui_sfml.s"
	@echo "... src/light/src/LightPoint.o"
	@echo "... src/light/src/LightPoint.i"
	@echo "... src/light/src/LightPoint.s"
	@echo "... src/light/tests/test_light_LightPoint.o"
	@echo "... src/light/tests/test_light_LightPoint.i"
	@echo "... src/light/tests/test_light_LightPoint.s"
	@echo "... src/main/main.o"
	@echo "... src/main/main.i"
	@echo "... src/main/main.s"
	@echo "... src/materials/src/Material.o"
	@echo "... src/materials/src/Material.i"
	@echo "... src/materials/src/Material.s"
	@echo "... src/materials/src/MaterialProperties.o"
	@echo "... src/materials/src/MaterialProperties.i"
	@echo "... src/materials/src/MaterialProperties.s"
	@echo "... src/materials/tests/test_materials_MaterialsProperties.o"
	@echo "... src/materials/tests/test_materials_MaterialsProperties.i"
	@echo "... src/materials/tests/test_materials_MaterialsProperties.s"
	@echo "... src/math/src/Quadratic.o"
	@echo "... src/math/src/Quadratic.i"
	@echo "... src/math/src/Quadratic.s"
	@echo "... src/math/tests/test_math_quadratic.o"
	@echo "... src/math/tests/test_math_quadratic.i"
	@echo "... src/math/tests/test_math_quadratic.s"
	@echo "... src/ray/src/CameraRay.o"
	@echo "... src/ray/src/CameraRay.i"
	@echo "... src/ray/src/CameraRay.s"
	@echo "... src/ray/src/Ray.o"
	@echo "... src/ray/src/Ray.i"
	@echo "... src/ray/src/Ray.s"
	@echo "... src/ray/src/ReflexionRay.o"
	@echo "... src/ray/src/ReflexionRay.i"
	@echo "... src/ray/src/ReflexionRay.s"
	@echo "... src/ray/src/ShadowRay.o"
	@echo "... src/ray/src/ShadowRay.i"
	@echo "... src/ray/src/ShadowRay.s"
	@echo "... src/ray/src/TransmissionRay.o"
	@echo "... src/ray/src/TransmissionRay.i"
	@echo "... src/ray/src/TransmissionRay.s"
	@echo "... src/ray/tests/test_ray_Ray.o"
	@echo "... src/ray/tests/test_ray_Ray.i"
	@echo "... src/ray/tests/test_ray_Ray.s"
	@echo "... src/scene/src/Intersection.o"
	@echo "... src/scene/src/Intersection.i"
	@echo "... src/scene/src/Intersection.s"
	@echo "... src/scene/src/Object.o"
	@echo "... src/scene/src/Object.i"
	@echo "... src/scene/src/Object.s"
	@echo "... src/scene/src/Scene.o"
	@echo "... src/scene/src/Scene.i"
	@echo "... src/scene/src/Scene.s"
	@echo "... src/scene/src/Shape.o"
	@echo "... src/scene/src/Shape.i"
	@echo "... src/scene/src/Shape.s"
	@echo "... src/scene/src/Sphere.o"
	@echo "... src/scene/src/Sphere.i"
	@echo "... src/scene/src/Sphere.s"
	@echo "... src/scene/tests/test_sphere_intersection.o"
	@echo "... src/scene/tests/test_sphere_intersection.i"
	@echo "... src/scene/tests/test_sphere_intersection.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

